spring.application.name=standupsync

# Database Configuration (Supabase PostgreSQL via session pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.gcxgfpjnccyfmmzhivmz
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server Port
server.port=8080
